#!/usr/bin/env python3
from rush.ex00.checkmate import chessboard
if __name__ == "__main__":
    board = """\
........
........
Q.......
......K.
.....P..
........
........
..P....."""
    chessboard(board) 